name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: recipe-analyzer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Uncomment to enable pushing to a registry
  # push:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name != 'pull_request'
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     
  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: yourusername/recipe-analyzer:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
