name: Build and Tag Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/recipe-ai-backend:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/recipe-ai-backend:latest
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Update version file
        run: |
          echo "${{ steps.get_version.outputs.VERSION }}" > backend/VERSION
